name: deploy

on:
  workflow_dispatch:
    inputs:
      parameter-name:
        description: 'Description of the parameter'
        required: true
        default: 'Default value'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Pull the image
        run: docker pull ghcr.io/antgenix1/careminder:latest

      - name: Run the container
        run: docker run -d -p 8080:80 ghcr.io/antgenix1/careminder:latest
