name: Build and copy files

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      # Setup frontend
      - name: Install all dependencies
        run: npm install
        working-directory: frontend/web

      - name: Build
        run: npm run build
        working-directory: frontend/web
